site_name: Mail Client Project
site_description: "A professional-grade template for a modern Python project."

theme:
  name: material
  palette:
    # Light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs
    - content.code.copy

nav:
  - 'Overview': 'index.md'
  - 'Architecture': 'component.md'
  - 'API Reference':
    - 'Message Protocol': 'api/message.md'
    - 'Mail Client API': 'api/mail_client_api.md'
    - 'Gmail Client Implementation': 'api/gmail_client_impl.md'
    - 'Gmail Message Implementation': 'api/gmail_message_impl.md'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            # This helps mkdocstrings find packages in the src directory
            search_paths: 
              - src/message/src
              - src/mail_client_api/src
              - src/gmail_client_impl/src
              - src/gmail_message_impl/src
            show_source: false
            docstring_section_style: spacy
            members_order: source
